version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - 5432:5432
  app:
    build: .
    ports:
      - 80:80
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
